Repository WebDevStudios/wds-blocks, pull requests merged in 2018-04, with the labels that each got.

#38 Feature/#27 bring in prettier
  .prettierrc
  package-lock.json
  package.json
Labels: enhancement

#40 Feature/editor styles to match front end
  README.md
  dist/blocks.build.js
  dist/blocks.editor.build.css
  dist/blocks.style.build.css
  src/blocks/call-to-action/editor.scss
  src/blocks/call-to-action/index.js
  src/blocks/default/editor.scss
  src/blocks/default/index.js
  src/blocks/default/style.scss
  src/blocks/github-gist/editor.scss
  src/blocks/github-gist/index.js
  src/blocks/github-gist/style.scss
  src/blocks/hero/editor.scss
  src/blocks/hero/index.js
  src/blocks/hero/style.scss
  src/blocks/two-column-block/editor.scss
  src/blocks/two-column-block/index.js
  src/blocks/two-column-block/style.scss
  src/common.scss
  src/components/button-link/editor.scss
  src/sass/_breakpoints.scss
  src/sass/_colors.scss
  src/sass/_fonts.scss
  src/sass/_full-width.scss
  src/sass/_global-blocks.scss
Labels: R4R

#41 Feature/#10 related posts block
  dist/blocks.build.js
  dist/blocks.editor.build.css
  dist/blocks.style.build.css
  src/blocks/related-posts/edit.js
  src/blocks/related-posts/editor.scss
  src/blocks/related-posts/index.js
  src/blocks/related-posts/item.js
  src/blocks/related-posts/output.js
  src/blocks/related-posts/post-render.js
  src/blocks/related-posts/render.php
  src/blocks/related-posts/style.scss
  src/components/block-title/editor.scss
  src/components/block-title/index.js
  src/components/loader/index.js
  src/components/post-search/attributes.js
  src/components/post-search/index.js
  src/components/search/index.js
Labels: R4R, enhancement
